services:
  # docker inspect voxacommunications-backend-registry-mysql-1 | grep IPAddress
  # network mode:voxacommunications-backend_default
  registry-mysql:
    image: mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registry
    ports:
      - "3308:3306"
    #volumes:
    #  - ./mysql-data:/var/lib/mysql